In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#read data
df = pd.read_csv('datasets/2018CrimeStatisticsByCategoryOfCrime.csv')

#check data
df.head()

,Unnamed: 0,Unnamed: 1,REPORTED CASES,Unnamed: 3,Unnamed: 4,Unnamed: 5,PERFOMANCE,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,VICTIMS OF CRIME,NaN,NaN,NaN,VALUE PROPERTY(UGSHS.),NaN
1,NaN,NaN,Totals Cases,Cases under Inquiry,Not Detected/NPW,Cases taken to court,Cases submitted toDPP/RSA,Cases with convictions,Cases with Acquittals,Cases Dismissed,...,Probation Bound Over,CAUTION,COMM. WORK,Fines Awarded (UgShs.),Male Adult,Male Juven.,Female Adult,Female Juven.,Lost,Recovered
2,S/No.,CASE/CRIME INCIDENCES,1,2,3,4,5,6,7,8,...,18,19,20,21,NaN,NaN,NaN,22,23,24
3,NaN,HOMICIDES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Death (by shooting),190,117,29,44,74,3,1,1,...,-,-,-,-,197,4,17,-,"11,500,000",-

In [4]:
#check for duplicates
df.duplicated().sum()

0

In [5]:
#check for missing values
df.isnull().sum()

Unnamed: 0                     32
Unnamed: 1                      2
REPORTED CASES                  2
Unnamed: 3                      2
Unnamed: 4                      2
Unnamed: 5                      2
PERFOMANCE                      2
Unnamed: 7                      2
Unnamed: 8                      2
Unnamed: 9                      2
Unnamed: 10                     2
PERSONS TAKEN TO COURT          1
Unnamed: 12                     3
Unnamed: 13                     3
Unnamed: 14                     3
Unnamed: 15                     1
Unnamed: 16                     3
Unnamed: 17                     3
Unnamed: 18                     3
Unnamed: 19                    18
Unnamed: 20                    18
Unnamed: 21                    18
SENTENCES IMPOSED BY COURTS    18
Unnamed: 23                    19
Unnamed: 24                    19
Unnamed: 25                    18
Unnamed: 26                    18
Unnamed: 27                    18
Unnamed: 28                    18
Unnamed: 29                    18
Unnamed: 30                    18
Unnamed: 31                    18
Unnamed: 32                    27
Unnamed: 33                    20
Unnamed: 34                    28
Unnamed: 35                    19
Unnamed: 36                    17
Unnamed: 37                    18
dtype: int64